
server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: consumer
          uri: lb://basic-consumer
          filters:
            - name: governance
          predicates:
            - Path=/**


consumer:
  config: gateway