

server:
  port: 8082


#consumer:
#  config: 123


provider:
  url: http://127.0.0.1:8080



consumer:
  config: abc


feign:
  interceptor:
    feignMapUrl:
      feignConsumerService: http://127.0.0.1:8086



logging:
  level:
    com:
      huaweicloud:
        samples:
          config:
            MyClient: INFO


spring:
  redis:
    host: 192.168.211.128
    port: 6379
    password: 123456



config:
  service:
    a:
      enable: true